[tool.poetry]
name = "adventofcode2024"
version = "0.1.0"
description = ""
authors = ["pkublas <pkublas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
